version: '3.8'

services:
  postgres:
    container_name: desafio-estacionamento
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio-estacionamento
#      PGDATA: /data/postgres
#    volumes:
#      - ./data/pg:/data/postgres
