spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/desafio-estacionamento
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

flyway:
  locations: classpath:db/migration

