@baseUrl = http://localhost:8081/access
@lisencePlateMotorcycle = "AAAA333"
@lisencePlateCar = "ABC1235"


### entry
POST {{baseUrl}}/entry
Content-Type: application/json

{
  "establishmentId": 19,
  "licensePlate": {{lisencePlateMotorcycle}}
}

### exit
POST {{baseUrl}}/exit
Content-Type: application/json

{
  "establishmentId": 19,
  "licensePlate": {{lisencePlateMotorcycle}}
}
