CREATE TABLE vehicle
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand         VARCHAR(255),
    model         VARCHAR(255),
    color         VARCHAR(255),
    license_plate VARCHAR(255),
    type          SMALLINT,
    CONSTRAINT pk_vehicle PRIMARY KEY (id)
);

DROP TABLE tb_vehicle CASCADE;

